version: '3'

services:

  ccenv:
    command: /bin/sh -c 'sleep 6000000'
    container_name: ccenv
    depends_on:
      - orderer
      - peer
    environment:
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_ID=pix
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
    image: hyperledger/fabric-ccenv
    tty: true
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
        - ./../chaincode:/opt/gopath/src/ccenv
    working_dir: /opt/gopath/src/ccenv

  orderer:
    command: orderer
    container_name: orderer
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - GRPC_TRACE=all=true
      - GRPC_VERBOSITY=debug
      - ORDERER_GENERAL_BOOTSTRAPFILE=orderer.block
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - ORDERER_GENERAL_LOCALMSPID=DEFAULT
    image: hyperledger/fabric-orderer
    ports:
      - 7050:7050
    volumes:
      - ./msp:/etc/hyperledger/msp
      - ./orderer.block:/etc/hyperledger/fabric/orderer.block
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric

  peer:
    command: peer node start --peer-chaincodedev=true
    container_name: peer
    depends_on:
      - orderer
    environment:
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_ID=peer
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
    image: hyperledger/fabric-peer
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer

  tools:
    command: /bin/bash -c './script.sh'
    container_name: tools
    depends_on:
      - orderer
      - peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_ID=tools
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - FABRIC_LOGGING_SPEC=DEBUG
      - GOPATH=/opt/gopath
    image: hyperledger/fabric-tools
    tty: true
    volumes:
      - /var/run/:/host/var/run/
      - ./msp:/etc/hyperledger/msp
      - ./../chaincode:/opt/gopath/src/chaincodedev/chaincode
      - ./:/opt/gopath/src/chaincodedev/
    working_dir: /opt/gopath/src/chaincodedev
